variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_TLS_CERTDIR: ''
  DOCKER_HOST: tcp://docker:2375  

cache:
  paths:
    - .m2/repository

services:
  - name : docker:20.10.16-dind
    entrypoint: ["dockerd-entrypoint.sh"]
    command: ["--insecure-registry","$CI_REGISTRY"]

stages:
  - build
  - test
  - package

maven-build:
  image: maven:3.6.3-openjdk-8
  stage: build
  before_script: "chmod +x mvnw"
  script: "./mvnw clean compile"

maven-test:
  image: maven:3.6.3-openjdk-8
  stage: test
  before_script: "chmod +x mvnw"
  script: "./mvnw test"

docker-build:
  image: docker:20.10.16
  stage: package
  before_script:
    - docker info
    - docker login -u "$TOKEN_USER" -p "$TOKEN_PW" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest